#!/usr/bin/env bash
set -euo pipefail

log() {
  echo "[wg-bootstrap] $*"
}

error() {
  echo "[wg-bootstrap] $*" >&2
}

usage() {
  cat <<'EOF'
Usage:
  bootstrap_wg_peer.sh <client-node-name> <peer-ip-cidr> <server-endpoint> <server-public-key>

Example:
  bootstrap_wg_peer.sh admin-laptop-01 10.100.0.2/32 vps.example.com:51820 AP+7itVxasJxKlmwofEE4jZ9NER553w/P38ZugairV4=

Environment overrides:
  WG_ENV=prod|lab|dr           (default: prod)
  WG_ROLE=peer|hub             (default: peer)
  WG_OUTPUT_DIR=<path>         (default: ~/wireguard-local)
  WG_ALLOWED_IPS=<cidr-list>   (default: 10.100.0.0/24)
  WG_DNS=<dns-ip>              (default: 1.1.1.1)
  WG_KEEPALIVE=<seconds>       (default: 25)
  WG_BIN=<wg-command>          (default: wg)
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 4 ]]; then
  usage
  exit 1
fi

CLIENT_NODE="$1"
PEER_IP_CIDR="$2"
SERVER_ENDPOINT="$3"
SERVER_PUBLIC_KEY="$4"

WG_ENV="${WG_ENV:-prod}"
WG_ROLE="${WG_ROLE:-peer}"
WG_OUTPUT_DIR="${WG_OUTPUT_DIR:-$HOME/wireguard-local}"
WG_ALLOWED_IPS="${WG_ALLOWED_IPS:-10.100.0.0/24}"
WG_DNS="${WG_DNS:-1.1.1.1}"
WG_KEEPALIVE="${WG_KEEPALIVE:-25}"
WG_BIN="${WG_BIN:-wg}"

if ! command -v "$WG_BIN" >/dev/null 2>&1; then
  error "wg command not found: $WG_BIN"
  error "Install wireguard-tools and retry."
  exit 1
fi

if [[ ! "$CLIENT_NODE" =~ ^[a-z0-9-]+$ ]]; then
  error "client node name must match ^[a-z0-9-]+$"
  exit 1
fi

if [[ ! "$PEER_IP_CIDR" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$ ]]; then
  error "peer-ip-cidr must look like 10.100.0.2/32"
  exit 1
fi

if [[ -z "$SERVER_ENDPOINT" || "$SERVER_ENDPOINT" != *:* ]]; then
  error "server-endpoint must look like host:port"
  exit 1
fi

if [[ ! "$SERVER_PUBLIC_KEY" =~ ^[A-Za-z0-9+/=]+$ ]]; then
  error "server-public-key must be base64-like"
  exit 1
fi

if [[ ! "$WG_KEEPALIVE" =~ ^[0-9]+$ ]]; then
  error "WG_KEEPALIVE must be an integer"
  exit 1
fi

mkdir -p "$WG_OUTPUT_DIR"

BASE_NAME="wg-${WG_ENV}-${WG_ROLE}-${CLIENT_NODE}"
PRIVATE_KEY_PATH="${WG_OUTPUT_DIR}/${BASE_NAME}.private"
PUBLIC_KEY_PATH="${WG_OUTPUT_DIR}/${BASE_NAME}.public"
CONF_PATH="${WG_OUTPUT_DIR}/${BASE_NAME}.conf"

for f in "$PRIVATE_KEY_PATH" "$PUBLIC_KEY_PATH" "$CONF_PATH"; do
  if [[ -e "$f" ]]; then
    error "file already exists: $f"
    error "refusing to overwrite existing artifacts"
    exit 1
  fi
done

(
  umask 077
  "$WG_BIN" genkey > "$PRIVATE_KEY_PATH"
)

"$WG_BIN" pubkey < "$PRIVATE_KEY_PATH" > "$PUBLIC_KEY_PATH"

PRIVATE_KEY_CONTENT="$(tr -d '\r\n' < "$PRIVATE_KEY_PATH")"
PUBLIC_KEY_CONTENT="$(tr -d '\r\n' < "$PUBLIC_KEY_PATH")"

(
  umask 077
  cat > "$CONF_PATH" <<EOF
# Generated by scripts/testing/bootstrap_wg_peer.sh
# Node: ${CLIENT_NODE}
# PublicKey (share on server): ${PUBLIC_KEY_CONTENT}

[Interface]
PrivateKey = ${PRIVATE_KEY_CONTENT}
Address = ${PEER_IP_CIDR}
DNS = ${WG_DNS}

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
Endpoint = ${SERVER_ENDPOINT}
AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${WG_KEEPALIVE}
EOF
)

log "generated: $CONF_PATH"
log "generated: $PUBLIC_KEY_PATH"
log "generated: $PRIVATE_KEY_PATH"
log "next step: import .conf in WireGuard client and then remove local key files when no longer needed"
