param(
    [Parameter(Mandatory = $true)]
    [string]$ClientNodeName,

    [Parameter(Mandatory = $true)]
    [string]$PeerIpCidr,

    [Parameter(Mandatory = $true)]
    [string]$ServerEndpoint,

    [Parameter(Mandatory = $true)]
    [string]$ServerPublicKey,

    [ValidateSet("prod", "lab", "dr")]
    [string]$EnvName = "prod",

    [ValidateSet("peer", "hub")]
    [string]$Role = "peer",

    [string]$OutputDir,

    [string]$AllowedIps = "10.100.0.1/32",

    [string]$Dns = "1.1.1.1",

    [int]$PersistentKeepalive = 25,

    [string]$WgCommand = "wg"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message)
    Write-Output "[wg-bootstrap] $Message"
}

function Fail {
    param([string]$Message)
    Write-Error "[wg-bootstrap] $Message"
    exit 1
}

function Test-NodeName {
    param([string]$Value)
    return ($Value -match '^[a-z0-9-]+$')
}

function Test-IpCidr {
    param([string]$Value)

    if ($Value -notmatch '^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$') {
        return $false
    }

    $ipPart, $prefix = $Value.Split('/')
    if ([int]$prefix -lt 0 -or [int]$prefix -gt 32) {
        return $false
    }

    foreach ($octet in $ipPart.Split('.')) {
        $parsed = 0
        if (-not [int]::TryParse($octet, [ref]$parsed)) {
            return $false
        }
        if ($parsed -lt 0 -or $parsed -gt 255) {
            return $false
        }
    }

    return $true
}

if (-not $OutputDir) {
    $documents = [Environment]::GetFolderPath("MyDocuments")
    if ([string]::IsNullOrWhiteSpace($documents)) {
        $documents = Join-Path $HOME "Documents"
    }
    $OutputDir = Join-Path $documents "wireguard-local"
}

if (-not (Test-NodeName -Value $ClientNodeName)) {
    Fail "ClientNodeName must match ^[a-z0-9-]+$"
}

if (-not (Test-IpCidr -Value $PeerIpCidr)) {
    Fail "PeerIpCidr must look like 10.100.0.2/32"
}

if (-not (Test-IpCidr -Value $AllowedIps)) {
    Fail "AllowedIps must look like CIDR (example: 10.100.0.1/32)"
}

if ([string]::IsNullOrWhiteSpace($ServerEndpoint) -or $ServerEndpoint -notmatch ':') {
    Fail "ServerEndpoint must look like host:port"
}

if ([string]::IsNullOrWhiteSpace($ServerPublicKey) -or $ServerPublicKey -notmatch '^[A-Za-z0-9+/=]+$') {
    Fail "ServerPublicKey must be base64-like"
}

if ($PersistentKeepalive -lt 0) {
    Fail "PersistentKeepalive must be >= 0"
}

$wgCmd = Get-Command $WgCommand -ErrorAction SilentlyContinue
if (-not $wgCmd) {
    Fail "wg command not found ($WgCommand). Install WireGuard tools and retry."
}

New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$baseName = "wg-$EnvName-$Role-$ClientNodeName"
$privatePath = Join-Path $OutputDir "$baseName.private"
$publicPath = Join-Path $OutputDir "$baseName.public"
$confPath = Join-Path $OutputDir "$baseName.conf"

foreach ($path in @($privatePath, $publicPath, $confPath)) {
    if (Test-Path $path) {
        Fail "File already exists: $path"
    }
}

$privateKey = & $WgCommand genkey
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace(($privateKey | Out-String))) {
    Fail "Failed to generate private key via wg genkey"
}
$privateKey = ($privateKey | Out-String).Trim()
Set-Content -Path $privatePath -Value $privateKey -NoNewline -Encoding ascii

$publicKey = $privateKey | & $WgCommand pubkey
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace(($publicKey | Out-String))) {
    Fail "Failed to derive public key via wg pubkey"
}
$publicKey = ($publicKey | Out-String).Trim()
Set-Content -Path $publicPath -Value $publicKey -NoNewline -Encoding ascii

$config = @"
# Generated by scripts/testing/bootstrap_wg_peer.ps1
# Node: $ClientNodeName
# PublicKey (share on server): $publicKey

[Interface]
PrivateKey = $privateKey
Address = $PeerIpCidr
DNS = $Dns

[Peer]
PublicKey = $ServerPublicKey
Endpoint = $ServerEndpoint
AllowedIPs = $AllowedIps
PersistentKeepalive = $PersistentKeepalive
"@

Set-Content -Path $confPath -Value $config -Encoding ascii

Write-Log "generated: $confPath"
Write-Log "generated: $publicPath"
Write-Log "generated: $privatePath"
Write-Log "next step: import .conf in WireGuard client and then remove local key files when no longer needed"
